run_list "recipe[apt]",
         "recipe[vim]",
         "recipe[curl]",
         "recipe[java::oracle-java7]",
         "recipe[tree]",
         "recipe[env]",
         "recipe[hadoop]",
         "recipe[htop]",
         "recipe[sysstat]",
         "recipe[youtube-dl]",
         "recipe[ffmpeg]",
         "recipe[links]"
